# Generated by Django 4.0 on 2022-07-17 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Network', '0002_personmodel_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='bloodgroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=15)),
                ('avatar', models.ImageField(default='avatar.png', upload_to='Profile_Image')),
                ('dateofbirth', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=150)),
                ('bloodgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Network.bloodgroup')),
            ],
        ),
    ]
