# Generated by Django 4.0 on 2022-07-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Network', '0003_bloodgroup_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImageUploading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='bloodgroup',
            new_name='blood',
        ),
    ]
